### ISSUE TITLE
Panic when SQL references a non-existent table

### ISSUE THREAD

**Issue by philrz** [brimdata/zq#2419]
Repro is with `zq` commit 28a347d and the [fruit sample data](https://github.com/mccanne/fruit).

While verifying #2215, I accidentally made a typo that ended up causing a panic. Note where I type `fuit` instead of `fruit`.

```
$ zq -z 'SELECT * FROM fuit f ORDER by f.name LIMIT 3' fruit.zson 
fatal error: sync: Unlock of unlocked RWMutex

goroutine 37 [running]:
runtime.throw(0x1959216, 0x20)
	/usr/local/opt/go/libexec/src/runtime/panic.go:1117 +0x72 fp=0xc0001619c8 sp=0xc000161998 pc=0x1039292
sync.throw(0x1959216, 0x20)
	/usr/local/opt/go/libexec/src/runtime/panic.go:1103 +0x35 fp=0xc0001619e8 sp=0xc0001619c8 pc=0x106b775
sync.(*RWMutex).Unlock(0xc0004548c0)
	/usr/local/opt/go/libexec/src/sync/rwmutex.go:142 +0xc6 fp=0xc000161a20 sp=0xc0001619e8 pc=0x108a266
github.com/brimsec/zq/zson.(*Context).LookupByName(0xc0004548c0, 0xc000134558, 0x7, 0x0, 0x0, 0x1ab8d40, 0xc00011a520)
	/Users/phil/work/zq/zson/context.go:258 +0x3ef fp=0xc000161ac0 sp=0xc000161a20 pc=0x1556a4f
github.com/brimsec/zq/expr/function.(*is).Call(0xc000122058, 0xc0001200a0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9, ...)
	/Users/phil/work/zq/expr/function/function.go:198 +0x17b fp=0xc000161b80 sp=0xc000161ac0 pc=0x15844fb
github.com/brimsec/zq/expr.(*Call).Eval(0xc0001200f0, 0xc000120280, 0x0, 0x0, 0x0, 0x0, 0x0, 0x2b405b8, 0x50)
	/Users/phil/work/zq/expr/eval.go:712 +0x1e8 fp=0xc000161c78 sp=0xc000161b80 pc=0x159cc68
github.com/brimsec/zq/compiler/kernel.compileExprPredicate.func1(0xc000120280, 0x0)
	/Users/phil/work/zq/compiler/kernel/filter.go:184 +0x67 fp=0xc000161d20 sp=0xc000161c78 pc=0x16f8507
github.com/brimsec/zq/proc/filter.(*Proc).Pull(0xc000118120, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/filter/filter.go:32 +0xb5 fp=0xc000161dc0 sp=0xc000161d20 pc=0x16daeb5
github.com/brimsec/zq/proc.(*applier).Pull(0xc000128280, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/apply.go:43 +0x1d9 fp=0xc000161e50 sp=0xc000161dc0 pc=0x16164b9
github.com/brimsec/zq/proc/sort.(*Proc).recordsForOneRun(0xc00012c0e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/sort/sort.go:102 +0x1ca fp=0xc000161f10 sp=0xc000161e50 pc=0x16d2fea
github.com/brimsec/zq/proc/sort.(*Proc).sortLoop(0xc00012c0e0)
	/Users/phil/work/zq/proc/sort/sort.go:58 +0x78 fp=0xc000161fd8 sp=0xc000161f10 pc=0x16d28d8
runtime.goexit()
	/usr/local/opt/go/libexec/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc000161fe0 sp=0xc000161fd8 pc=0x1070be1
created by github.com/brimsec/zq/proc/sort.(*Proc).Pull.func1
	/Users/phil/work/zq/proc/sort/sort.go:45 +0x3e

goroutine 1 [select]:
github.com/brimsec/zq/driver.(*muxOutput).Pull(0xc000120140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/driver/mux.go:105 +0x17f
github.com/brimsec/zq/driver.runMux(0xc000120140, 0x1ac9378, 0xc00011e0f0, 0x0, 0xc0001ae1f8, 0xc00021faa0)
	/Users/phil/work/zq/driver/driver.go:63 +0x8a
github.com/brimsec/zq/driver.Run(0x1ac9618, 0xc0004692f0, 0x1ac9378, 0xc00011e0f0, 0x1ab9580, 0xc0004687e0, 0xc0001ae1f8, 0x1aba0a0, 0xc0004692c0, 0x0, ...)
	/Users/phil/work/zq/driver/driver.go:33 +0x1cd
main.(*Command).Run(0xc00029f1e0, 0xc0001b2020, 0x2, 0x2, 0x0, 0x0)
	/Users/phil/work/zq/cmd/zq/zq.go:197 +0xbcc
github.com/mccanne/charm.(*instance).run(0xc0001d5420, 0xc0001b2010, 0x3, 0x3, 0x0, 0x0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/instance.go:53 +0x2a2
github.com/mccanne/charm.(*Spec).ExecRoot(0x1f26f80, 0xc0001b2010, 0x3, 0x3, 0xc00021ff78, 0x1007865, 0xc000182058, 0x10014b0)
	/Users/phil/.go/pkg/mod/github.com/mccanne/charm@v0.0.3-0.20191224190439-b05e1b7b1be3/charm.go:77 +0x99
main.main()
	/Users/phil/work/zq/cmd/zq/main.go:9 +0x85

goroutine 34 [syscall]:
os/signal.signal_recv(0x0)
	/usr/local/opt/go/libexec/src/runtime/sigqueue.go:165 +0x9d
os/signal.loop()
	/usr/local/opt/go/libexec/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/usr/local/opt/go/libexec/src/os/signal/signal.go:151 +0x45

goroutine 35 [select]:
github.com/brimsec/zq/pkg/signalctx.New.func1(0xc000411320, 0xc0004692f0, 0xc000463fc0, 0x1ac90d8, 0xc0003f75c0)
	/Users/phil/work/zq/pkg/signalctx/signalctx.go:25 +0xad
created by github.com/brimsec/zq/pkg/signalctx.New
	/Users/phil/work/zq/pkg/signalctx/signalctx.go:24 +0x12f

goroutine 36 [chan receive]:
github.com/brimsec/zq/proc/sort.(*Proc).Pull(0xc00012c0e0, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/sort/sort.go:46 +0x7a
github.com/brimsec/zq/proc/head.(*Proc).Pull(0xc00012e260, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/proc/head/head.go:26 +0x7f
github.com/brimsec/zq/driver.(*mux).safeGet(0xc00012e280, 0x0, 0x0, 0x0, 0x0)
	/Users/phil/work/zq/driver/mux.go:51 +0x6c
github.com/brimsec/zq/driver.(*mux).run(0xc00012e280)
	/Users/phil/work/zq/driver/mux.go:64 +0x32
created by github.com/brimsec/zq/driver.(*muxOutput).Pull.func1
	/Users/phil/work/zq/driver/mux.go:98 +0x5d
```

**Comment by philrz** [comment]
Verified in `zq` commit c4cedfe.

Now we get the expected error message without a panic.

```
$ zq -version
Version: v0.29.0-176-gc4cedfea

$ zq -z 'SELECT * FROM fuit f ORDER by f.name LIMIT 3' fruit.zson
cut: no record found with columns .
```

Thanks @mccanne!
